name: Test
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.vi }} / ${{ matrix.cp }}, ${{ matrix.dl }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-11]
        vi: [neovim, vim]
        cp: [system, copy, hardlink, symlink]
        dl: [git, curl, wget]
    steps:
      - id: check
        if: ${{ (matrix.os == 'windows-2022' && matrix.dl == 'wget') ||
                (matrix.vi == 'vim' && contains(matrix.cp, 'link')) }}
        run: echo 'Unsupported environment'

      - name: Clone vim-jetpack
        uses: actions/checkout@v2
        if: ${{ steps.check.conclusion == 'skipped' }}

      - name: Install vim-themis
        uses: actions/checkout@v2
        if: ${{ steps.check.conclusion == 'skipped' }}
        with:
          repository: thinca/vim-themis
          path: vim-themis

      - name: Install Vim
        uses: rhysd/action-setup-vim@v1
        if: ${{ steps.check.conclusion == 'skipped' && matrix.vi == 'vim' }}
        id: vim
        with:
          version: 'v8.1.2424'
          neovim: 'false'
      - name: Run Vim tests with ${{ matrix.dl }} and ${{ matrix.cp }}
        if: ${{ steps.check.conclusion == 'skipped' && matrix.vi == 'vim' }}
        timeout-minutes: 5
        env:
          JETPACK_DOWNLOAD_METHOD: ${{ matrix.dl }}
          JETPACK_COPY_METHOD: ${{ matrix.cp }}
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: ./vim-themis/bin/themis ./test/test.vim

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        if: ${{ steps.check.conclusion == 'skipped' && matrix.vi == 'neovim' }}
        id: neovim
        with:
          version: 'stable'
          neovim: 'true'
      - name: Run Neovim tests with ${{ matrix.dl }} and ${{ matrix.cp }}
        if: ${{ steps.check.conclusion == 'skipped' && matrix.vi == 'neovim' }}
        timeout-minutes: 5
        env:
          JETPACK_DOWNLOAD_METHOD: ${{ matrix.dl }}
          JETPACK_COPY_METHOD: ${{ matrix.cp }}
          THEMIS_VIM: ${{ steps.neovim.outputs.executable }}
        run: ./vim-themis/bin/themis ./test/test.vim

  post-test:
    name: All tests passed
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - run: echo ok
