name: Test
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.vi }} / ${{ matrix.cp }}, ${{ matrix.dl }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
        vi: [neovim, vim]
        cp: [system, copy, hardlink, symlink]
        dl: [git, curl, wget]
        ver: [stable, v8.1.2110]
        exclude:
          - vi: vim
            ver: stable
            os: ubuntu-22.04
          - vi: neovim
            ver: v8.1.2110
          - os: windows-2022
            ver: v8.1.2110
          - os: macos-12
            ver: v8.1.2110
          - os: windows-2022
            dl: wget
          - vi: vim
            cp: symlink
          - vi: vim
            cp: hardlink
    steps:
      - name: Clone vim-jetpack
        uses: actions/checkout@v3

      - name: Install Lua
        if: ${{ contains(matrix.os, 'windows') }}
        run: |
          Invoke-WebRequest -Uri https://joedf.ahkscript.org/LuaBuilds/hdata/lua-5.4.4_Win64_bin.zip -OutFile .\Lua.zip
          Expand-Archive .\Lua.zip C:\Lua
          Add-Content $env:GITHUB_PATH C:\Lua

      - name: Install vim-themis
        uses: actions/checkout@v3
        with:
          repository: thinca/vim-themis
          path: vim-themis

      - name: Install ${{ matrix.vi }}
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: ${{ matrix.ver }}
          neovim: ${{ matrix.vi == 'neovim' }}

      - name: Run tests with ${{ matrix.dl }} and ${{ matrix.cp }}
        timeout-minutes: 5
        env:
          JETPACK_DOWNLOAD_METHOD: ${{ matrix.dl }}
          JETPACK_COPY_METHOD: ${{ matrix.cp }}
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: ./vim-themis/bin/themis ./test/test.vim
  post-test:
    name: All tests passed
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - run: echo ok
