name: Test
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.vi }} / ${{ matrix.cp }}, ${{ matrix.dl }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
        vi: [neovim, vim]
        cp: [system, copy, hardlink, symlink]
        dl: [git, curl, wget]
        exclude:
          - os: windows-2022
            dl: wget
          - vi: vim
            cp: symlink
          - vi: vim
            cp: hardlink
    steps:
      - name: Clone vim-jetpack
        uses: actions/checkout@v2

      - name: Install Lua
        uses: leafo/gh-actions-lua@v9
        if: ${{ contains(matrix.os, 'windows') }}
        with:
          luaVersion: "5.4.4"

      - name: Install vim-themis
        uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis

      - name: Install ${{ matrix.vi }}
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: ${{ (matrix.vi == 'vim' && matrix.os == 'ubuntu-20.04') && 
                       'v8.1.2110' || 'stable' }}
          neovim: ${{ matrix.vi == 'neovim' }}

      - name: Run tests with ${{ matrix.dl }} and ${{ matrix.cp }}
        timeout-minutes: 5
        env:
          JETPACK_DOWNLOAD_METHOD: ${{ matrix.dl }}
          JETPACK_COPY_METHOD: ${{ matrix.cp }}
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: ./vim-themis/bin/themis ./test/test.vim
  post-test:
    name: All tests passed
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - run: echo ok
